export enum Cities {
  ARAMBARE = "Arambaré",
  ARROIO_DOS_RATOS = "Arroio dos Ratos",
  BARAO_DO_TRINUFO = "Barão do Triunfo",
  BARRA_DO_RIBEIRO = "Barra do Ribeiro",
  BUTIA = "Butiá",
  CAMAQUA = "Camaquã",
  CERRO_GRANDE_DO_SUL = "Cerro Grande do Sul",
  CHARQUEADAS = "Charqueadas",
  CHUVISCA = "Chuvisca",
  CRISTAL = "Cristal",
  DOM_FELICIANO = "Dom Feliciano",
  ELDORADO_DO_SUL = "Eldorado do Sul",
  GENERAL_CAMARA = "General Câmara",
  GUAIBA = "Guaíba",
  MARIANA_PIMENTEL = "Mariana Pimentel",
  MINAS_DO_LEAO = "Minas do Leão",
  SAO_JERONIMO = "São Jerônimo",
  SENTINELA_DO_SUL = "Sentinela do Sul",
  SERTAO_SANTANA = "Sertão Santana",
  TAPES = "Tapes"
} 